# Dev
org.gradle.jvmargs=-Xmx2G

# Mod - All field required.
mod.name=Interactive Guns
mod.id=interactiveguns
mod.group=com.example
mod.version=0.0.1
mod.author=timtaran
mod.description=Guns in VR
mod.license=GPL-3.0
mod.github=https://github.com/timtaran/InteractiveGuns

# Stonecutter
stonecutter_enabled_platforms=fabric, neoforge
stonecutter_enabled_common_versions=1.21.1
stonecutter_enabled_fabric_versions=1.21.1
stonecutter_enabled_forge_versions=
stonecutter_enabled_neoforge_versions=1.21.1

# The below field are intentionally left blank,
# to edit, please edit gradle.properties for each versions.

# Java
java.version=

# Minecraft
minecraft_version=
min_minecraft_version=

# Mappings
deps.parchment=

# Fabric https://fabricmc.net/versions.html
deps.fabric-loader=
deps.fabric-api=

# Forge
deps.forge=

# NeoForge https://projects.neoforged.net/neoforged/neoforge
deps.neoforge=

# Dependencies
deps.modmenu=
deps.vivecraft=
deps.yacl=
deps.lwjgl=
deps.velthoric=
deps.interactivemc=